"use client";

import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";

import {
  generateMissionBriefAction,
  type MissionBriefFormState,
} from "@/app/missions/[missionId]/copilot-actions";
import { formatTenthCentsUsd } from "@/lib/copilot/pricing";

type Props = {
  missionId: string;
  missionName: string;
  /** True when both the env kill-switch and the per-org opt-in are on. */
  available: boolean;
  availabilityHint: string;
};

const INITIAL: MissionBriefFormState = { status: "idle" };

function SubmitButton({ disabled }: { disabled: boolean }) {
  const { pending } = useFormStatus();
  return (
    <button
      type="submit"
      disabled={disabled || pending}
      className="button button-primary"
    >
      {pending ? "Drafting brief…" : "Generate client brief"}
    </button>
  );
}

function blockedMessage(state: MissionBriefFormState): string | null {
  if (state.status !== "blocked") return null;
  switch (state.reason) {
    case "not-authenticated":
      return "Sign in is required to generate a copilot brief.";
    case "not-authorized":
      return "Your role does not include copilot.generate. Ask an admin.";
    case "global-disabled":
      return "Aerial Copilot is disabled on this deployment (env kill-switch).";
    case "missing-api-key":
      return "Aerial Copilot is missing its AI Gateway credentials. Check server config.";
    case "org-disabled":
      return "Aerial Copilot is off for this organization. An admin can enable it in org settings.";
    case "mission-not-found":
      return "This mission could not be loaded for your org.";
    case "no-facts":
      return "No citable facts were found for this mission yet. Complete ingest/processing first.";
    case "quota-exhausted": {
      const spent = formatTenthCentsUsd(state.spendTenthCents ?? 0);
      const cap = formatTenthCentsUsd(state.capTenthCents ?? 0);
      return `Monthly copilot quota exhausted (${spent} of ${cap} used). Wait for the month to reset or raise the cap.`;
    }
    default:
      return "Copilot call was blocked.";
  }
}

function refusedMessage(state: MissionBriefFormState): string | null {
  if (state.status !== "refused") return null;
  switch (state.reason) {
    case "too-many-dropped":
      return `Brief refused: ${state.droppedSentences} of ${state.totalSentences} sentences failed citation grounding. Try again or check the underlying data.`;
    case "too-short":
      return "Brief refused: the grounded output was too short to be useful.";
    case "empty-output":
      return "Brief refused: the model produced no citable sentences.";
  }
}

function BriefResult({
  state,
  missionName,
}: {
  state: MissionBriefFormState;
  missionName: string;
}) {
  const [copied, setCopied] = useState(false);
  if (state.status !== "ok") return null;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(state.text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const markdown = `# ${missionName} — Mission Brief\n\n${state.text}\n\n---\n*Generated by Aerial Copilot (${state.modelId}). ${state.keptSentences} of ${state.totalSentences} sentences kept after grounding.*\n`;

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${missionName.replace(/\s+/g, "_")}_brief.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="copilot-result stack-sm">
      <p className="copilot-result-text">{state.text}</p>
      <div className="copilot-meta">
        <button
          type="button"
          onClick={handleCopy}
          className="button button-secondary"
        >
          {copied ? "Copied" : "Copy"}
        </button>
        <button
          type="button"
          onClick={handleDownload}
          className="button button-secondary"
        >
          Download .md
        </button>
        <span>
          {state.keptSentences}/{state.totalSentences} sentences kept · spend{" "}
          {formatTenthCentsUsd(state.spendTenthCents)} · model {state.modelId}
        </span>
      </div>
    </div>
  );
}

export function MissionBriefPanel({ missionId, missionName, available, availabilityHint }: Props) {
  const [state, formAction] = useActionState(generateMissionBriefAction, INITIAL);

  const blocked = blockedMessage(state);
  const refused = refusedMessage(state);

  return (
    <section className="surface stack-sm">
      <header className="stack-xs">
        <div>
          <h3>Aerial Copilot — Mission Brief</h3>
          <p className="muted helper-copy">
            One-click ~250-word client brief. Every sentence cites a real record; ungrounded claims
            are dropped. AI-assisted draft — review before sharing externally.
          </p>
        </div>
      </header>

      {!available ? (
        <p className="callout callout-warning">
          {availabilityHint}
        </p>
      ) : (
        <form action={formAction} className="header-actions">
          <input type="hidden" name="missionId" value={missionId} />
          <SubmitButton disabled={!available} />
          {state.status === "error" ? (
            <span className="copilot-inline-error">Error: {state.message}</span>
          ) : null}
        </form>
      )}

      {blocked ? (
        <p className="callout callout-warning">
          {blocked}
        </p>
      ) : null}
      {refused ? (
        <p className="callout callout-error">
          {refused}
        </p>
      ) : null}

      <BriefResult state={state} missionName={missionName} />
    </section>
  );
}
